#!/bin/bash
w=$(xdotool getdisplaygeometry | awk '{print $1}')
h=$(xdotool getdisplaygeometry | awk '{print $2}')
display_geometry="${w}x${h}"

prev="false"
i3-msg -t subscribe -m '[ "window" ]' | while read _; do
	win_geometry=$(xdotool getactivewindow getwindowgeometry | grep "Geometry:" | awk '{print $2}')
	[[ $win_geometry = $display_geometry ]] && is_fullscreen=true || is_fullscreen=false
	if [[ $is_fullscreen != $prev ]]; then
		[[ $is_fullscreen = "true" ]] && eww close bar 2> /dev/null && i3-msg gaps left all set 0		
		[[ $is_fullscreen = "false" ]] && eww open bar && i3-msg gaps left all set 50
	fi
	prev=$is_fullscreen
done

# vim: set ft=sh:
