#!/usr/bin/env python3
from i3ipc import Event, Connection

def no_borders(i3, e):
	def ignore(leaf):
		EXCLUDE = [
			("window_class", "stalonetray"),
			("window_class", "Nextcloud")
		]
		for k,v in EXCLUDE:
			if getattr(leaf, k) == v:
				return True
		return False
	workspace = i3.get_tree().find_focused().workspace()
	for leaf in workspace.leaves():
		# print(f"{leaf.window_class}, {leaf.window_title}: {leaf.focused}")
		if leaf.focused and not ignore(leaf):
			leaf.command("border pixel 3")
		else:
			leaf.command("border none")

def float_terminal(i3, e):
	win = i3.get_tree().find_focused()
	if win.window_class == "Alacritty" and win.window_instance == "floating":
		win.command("floating enable")

i3 = Connection()
i3.on(Event.WINDOW_FOCUS, no_borders)
i3.on(Event.WINDOW_NEW, float_terminal)
i3.main()
