#!/bin/bash

SCRIPTDIR="$HOME/.config/eww/scripts"

while [[ -n "$(pgrep i3lock)" ]]; do
	sleep .1
done
eww update hour="$(date +%H)"
eww update min="$(date +%M)"
eww update vol-icon="$($SCRIPTDIR/geticon vol)"
eww update cpu-val="$($SCRIPTDIR/getval cpu)"
eww update batt-val="$($SCRIPTDIR/getval batt)"
eww update batt-icon="$($SCRIPTDIR/geticon batt)"
eww update wifi-icon="$($SCRIPTDIR/geticon wifi)"
# $HOME/.config/i3/scripts/theme auto

# vim: set ft=sh:
