#!/bin/sh
USER=user
HOME=/home/user
case "$1" in
    pre)
    su - $USER --shell=/bin/sh -c '
		export DISPLAY=:0;
		export XDG_RUNTIME_DIR=/run/user/1000;
		$HOME/.config/i3/scripts/poweractions lock
		sleep 0.5
		'
    ;;
    post)
    su - $USER --shell=/bin/sh -c '
		export DISPLAY=:0;
		export XDG_RUNTIME_DIR=/run/user/1000;
		eww update hour="$(date +%H)";
		eww update min="$(date +%M)";
		eww update batt-val="$(~/.config/eww/scripts/getval batt)";
		eww update batt-icon="$(~/.config/eww/scripts/geticon batt)";
		'
    ;;
esac
