#!/bin/bash
pkill dunst
dunst &
sleep 0.1
notify-send -u critical "Test message" "Critical test 1"
notify-send -u normal "Test message" "Normal test 2"
#notify-send -u low "Test message" "Low test 3"
#notify-send -h int:value:42 "Working ..."
#notify-send -u critical "Test message: critical test 4"
#notify-send -u normal "Test message: normal test 5"
#notify-send -u low "Test message: low test 6"
#notify-send -u critical "Test message: critical test 7"
#notify-send -u normal "Test message: normal test 8"
#notify-send -u low "Test message: low test 9"
