#!/bin/bash
# Reference:
# https://github.com/ankkax/hyprland/blob/main/eww/bar/scripts/cava-internal.sh

# make sure to clean pipe
pipe="/tmp/cava.fifo"
if [ -p $pipe ]; then
    unlink $pipe
fi
mkfifo $pipe

# write cava config
config_file="/tmp/bar_cava_config"
echo "
[general]
bars = 12
framerate=30
autosens = 1
[output]
channels = mono
method = raw
raw_target = $pipe
data_format = ascii
ascii_max_range = 100
" > $config_file

# run cava in the background
cava -p $config_file &

# reading data from fifo
while read -r cmd; do
	IFS=';' read -ra arr <<< "$cmd"
	for i in "${!arr[@]}"; do
		[[ ${arr[$i]} =~ ^(0|1|2)$ ]] && arr[$i]=3
	done
	IFS=','; echo "[${arr[*]}]"	
	# s=$(sed 's/\;/,/g; s/,0/,3/g' <<< ",${cmd}")
	# echo "[${s:1:-1}]"
    # echo -ne "$cmd\r" | sed $dict
done < $pipe
