#!/bin/bash
# Reference:
# https://github.com/ankkax/hyprland/blob/main/eww/bar/scripts/cava-internal.sh

get_source_sink() {
	if [[ -n $(pactl list short sinks | grep bluez) ]]; then
		if [[ -n $(pactl list short sinks | grep virtual_sink) ]]; then
			echo "virtual_sink.monitor"
			return
		fi
		pactl load-module module-null-sink sink_name=virtual_sink
		bluez_sink=$(pactl list short sinks | grep bluez | awk '{print $2}')
		pactl load-module module-loopback latency_msec=1 source=$bluez_sink.monitor sink=virtual_sink
		echo "virtual_sink.monitor"
	else
		echo "auto"
	fi
}

# make sure to clean pipe
pipe="/tmp/cava.fifo"
if [ -p $pipe ]; then
    unlink $pipe
fi
mkfifo $pipe

# write cava config
config_file="/tmp/bar_cava_config"
source_sink=$(get_source_sink)
echo "
[general]
bars = 12
framerate=30
autosens = 1
[input]
method = pulse
source = $source_sink
[output]
channels = mono
method = raw
raw_target = $pipe
data_format = ascii
ascii_max_range = 100
" > $config_file

# run cava in the background
cava -p $config_file &

# reading data from fifo
while read -r cmd; do
	IFS=';' read -ra arr <<< "$cmd"
	for i in "${!arr[@]}"; do
		[[ ${arr[$i]} =~ ^(0|1|2)$ ]] && arr[$i]=3
	done
	IFS=','; echo "[${arr[*]}]"	
	# s=$(sed 's/\;/,/g; s/,0/,3/g' <<< ",${cmd}")
	# echo "[${s:1:-1}]"
    # echo -ne "$cmd\r" | sed $dict
done < $pipe
