#!/bin/bash

if [[ $1 = "wifi" ]]; then
	status="$(nmcli radio wifi)"
	[[ $status = "enabled" ]] && echo "selected" || echo ""

elif [[ $1 = "bluetooth" ]]; then
	status=$(systemctl status bluetooth | grep 'Active:' | awk '{print $2}')
	[[ $status = "active" ]] && echo "selected" || echo ""

elif [[ $1 = "notif" ]]; then
	status=$(dunstctl is-paused)
	[[ $status = "true" ]] && echo "selected" || echo ""

elif [[ $1 = "mute" ]]; then
	mute=$(pactl get-sink-mute @DEFAULT_SINK@)
	[[ $mute = "Mute: yes" ]] && echo "disabled" || echo ""

fi
