#!/bin/bash

batt_icons=("" "" "" "" "" "")
light_icons=("" "" "")

if [[ $1 = "vol" ]]; then
	mute=$(pactl get-sink-mute @DEFAULT_SINK@)
	if [[ $mute = "Mute: no" ]]; then
		[[ "$(eww get vol-tooltip | awk '{print $2}')" != "Speaker" ]] && 
			echo "" || echo ""
	else
		echo ""
	fi

elif [[ $1 = "light" ]]; then
	level=$(~/.config/eww/scripts/getval light)
	if [[ level -le 30 ]]; then ramp=0;
	elif [[ level -le 60 ]]; then ramp=1;
	else ramp=2; fi
	echo "${light_icons[$ramp]}"

elif [[ $1 = "batt" ]]; then
	status=$(cat /sys/class/power_supply/BAT1/status)
	if [[ $status = "Charging" ]]; then
		echo ""
		exit 0
	fi
	level=$(eww get batt-val)
	if [[ level -ge 99 ]]; then
		echo ""
		exit 0
	fi
	if [[ level -le 15 ]]; then ramp=0;
	elif [[ level -le 30 ]]; then ramp=1;
	elif [[ level -le 50 ]]; then ramp=2;
	elif [[ level -le 70 ]]; then ramp=3;
	elif [[ level -le 95 ]]; then ramp=4;
	else ramp=5; fi
	echo "${batt_icons[$ramp]}"

elif [[ $1 = "wifi" ]]; then
	eth=$(nmcli | grep "enp4s0f3u2" | awk '{print $2}')
	[[ $eth != "disconnected" ]] && [[ $eth != "" ]] && echo "" && exit 0
	[[ "$(iwgetid -r)" = "" ]] && echo "睊" && exit 0
	echo "直"

elif [[ $1 = "sync" ]]; then
	[[ $2 = "syncing" ]] && echo "" && exit 0
	[[ $2 = "off" ]] && echo "" && exit 0
	echo ""

fi
