#!/bin/bash

c1="Sync OneDrive (Personal)"
c2="Sync OneDrive (Imperial)"
c3="Sync all"
CHOICES="$c1\n$c2\n$c3"

run() {
	choice=$(echo -e "$CHOICES" | rofi -dmenu -theme ~/.config/rofi/dunst.rasi)
	case "$choice" in
		"$c1") systemctl --user restart onedrive;;
		"$c2") systemctl --user restart onedrive_imperial;;
		"$c3") systemctl --user restart onedrive && systemctl --user restart onedrive_imperial;;
	esac
	eww update sync-icon="$(~/.config/eww/scripts/geticon sync)"
	eww update sync-tooltip="$(~/.config/eww/script/tooltip sync)"
}

[[ $1 = "run" ]] && run && exit

alacritty --class Alacritty,minimized -e ~/.config/eww/scripts/sync run
