#!/bin/bash

if [[ $1 = "vol" ]]; then
	sink=$(pactl get-default-sink)
	if [[ $sink = "bluez"* ]]; then
		id=$(echo $sink | awk -F '[.]' '{print $2}' | tr '_' ':')
		name=$(bluetoothctl info $id | grep -Po 'Name:\s\K.*')
	elif [[ $sink = "alsa_output"* ]]; then
		name=$(pactl list sinks | grep -oP '(?<=Active Port: \[Out\] ).*')
	fi
	echo -e "Output: $name"

elif [[ $1 = "batt" ]]; then
	duration=$(acpi -b | awk -F '[,]' '{print $3}' | awk -F ' ' '{print $1}')
	status=$(cat /sys/class/power_supply/BAT1/status)
	[[ $status = "Charging" ]] && status_tooltip="till full" || status_tooltip="left"
	volt=$(cat /sys/class/power_supply/BAT1/voltage_now)
    curr=$(cat /sys/class/power_supply/BAT1/current_now)
    watt=$(echo "scale=2; ${volt}*${curr}/1000000/1000000" | bc)
	echo -e "Time: ${duration%:*} ${status_tooltip}\nRate: $watt W"

elif [[ $1 = "wifi" ]]; then
	dev="enp4s0f3u2"
	eth=$(nmcli | grep $dev | awk '{print $2}')
	if [[ $eth != "disconnected" ]] && [[ $eth != "" ]]; then
		name=$(nmcli | grep $dev | head -n 1 | grep -oP '(?<=connected to).*')
	else
		name=$(iwgetid -r)
		dev="wlp3s0"
	fi
	if [[ $name != "" ]]; then
		ip=$(ip addr show dev $dev | grep "inet " | awk '{print $2}')
		echo -e "Network: $name\nIP: $ip"
	fi

elif [[ $1 = "sync" ]]; then
	status_personal="$(systemctl --user status onedrive | grep "Active" | awk '{print $2}')"
	status_imperial="$(systemctl --user status onedrive_imperial | grep "Active" | awk '{print $2}')"
	if [[ $status_personal != "active" ]] && [[ $status_imperial != "active" ]]; then
		echo "OneDrive inactive"
	elif [[ $status_imperial != "active" ]]; then
		echo "OneDrive (Imperial) sync not active"
	elif [[ $status_personal != "active" ]]; then
		echo "OneDrive (Personal) sync not active"
	else
		echo "Both OneDrives are active"
	fi

fi
