#!/bin/bash
ICONPATH="$HOME/.config/eww/assets/$(~/.config/i3/scripts/theme -p)"
APIKEY=69b57cf8a44f5be52323699f6c9f611a
lim=15

# $1=str, $2=lim
wrapline() {
	[[ ${#1} -le $2 ]] && echo $1 && return
	l1="${1:0:$2}" && l1="${l1% *}"
	l2=$(echo $1 | grep -oP "(?<=${l1} ).*")
	[[ ${#l2} -gt $2 ]] && l2="${l2:0:11}..."
	echo -e "$l1\n$l2"
}

ip=$(curl -s https://ipinfo.io/ip)
locdata=$(curl -s "https://ipinfo.io/$ip")
if [[ $1 = "location" ]]; then
	city=$(echo "$locdata" | jq '.city' | tr -d '"')
	[[ ! -n "$city" ]] && echo "~" || wrapline "$city" $lim
	exit 0
fi

loc=$(echo "$locdata" | jq '.loc' | tr -d '"')
lat=$(echo "$loc" | awk -F ',' '{printf "%.2f", $1}')
lon=$(echo "$loc" | awk -F ',' '{printf "%.2f", $2}')

data=$(curl -s "https://api.openweathermap.org/data/2.5/weather?lat=${lat}&lon=${lon}&units=metric&appid=${APIKEY}")

if [[ $(echo "$data" | jq '.cod') != 200 ]]; then
	icon="$ICONPATH/unknown.svg"
	temp=""
	desc="Weather data not available"
fi

attrs=$(echo "$data" | jq '"\(.main.temp)|\(.weather[0].icon)|\(.weather[0].main), \(.weather[0].description)"' | tr -d '"')
temp=$(echo "$attrs" | awk -F'|' '{printf "%d", $1}')
icon=$(echo "$attrs" | awk -F'|' '{print $2}')
desc=$(echo "$attrs" | awk -F'|' '{print $3}')

if [[ $1 = "icon" ]]; then
	echo "$ICONPATH/${icon}.svg"

elif [[ $1 = "temp" ]]; then
    echo "${temp}°C"

elif [[ $1 = "cond" ]]; then
	[[ $2 != "short" ]] && echo "$desc" && exit 0
	cond=$(echo "$desc" | awk -F',' '{print $1}')
	wrapline "$cond" "$lim"

fi
