#!/bin/bash

if [[ $1 = "location" ]]; then
	## requires API access token
	ip=$(curl https://ipinfo.io/ip)
	city=$(curl "https://ipinfo.io/$ip" | grep "city" | awk '{print $2}' | grep -oP '(?<=").*(?=")')
	[[ -n $city ]] && echo $city || echo "~"
#	region=$(curl https://ipinfo.io/$ip | grep "region" | awk '{print $2}' | grep -oP '(?<=").*(?=")')
#	if [[ $city = $region ]]; then location=$region
#	else location="$city, $region"; fi
	# location="Pasir Panjang"
	# echo $location
	exit 0
fi

loc="$(~/.config/eww/scripts/weather location)"
cm1=$(curl wttr.in/$loc?format=%t-%c-%C 2> /dev/null) # suppress curl output
IFS="-" read -r temp icon cond <<< "$cm1" 2> /dev/null # suppress "Unknown..."
#echo $cm1

if [[ $icon = "" ]] || [[ $icon =~ [0-9] ]] ; then
	icon=""
	temp=""
	cond="Weather data not available"
fi

ICONS=("" "" "" "" "" "" "🌦")
if [[ $1 = "icon" ]]; then
	case $icon in
		⛅️*) echo "" ;;
		☀️*) echo "" ;;
		*) echo $icon ;;
	esac
elif [[ $1 = "temp" ]]; then
    echo $temp
elif [[ $1 = "cond" ]]; then
	[[ $2 != "short" ]] && echo $cond && exit 0
	lim=15
	[[ ${#cond} -le $lim ]] && echo $cond && exit 0
	l1="${cond:0:$lim}" && l1="${l1% *}"
	l2=$(echo $cond | grep -oP "(?<=${l1} ).*")
	[[ ${#l2} -gt $lim ]] && l2="${l2:0:11}..."
	echo -e "$l1\n$l2"

fi
