#!/bin/bash
lim=15

# $1=str, $2=lim
wrapline() {
	[[ ${#1} -le $2 ]] && echo $1 && return
	l1="${1:0:$2}" && l1="${l1% *}"
	l2=$(echo $1 | grep -oP "(?<=${l1} ).*")
	[[ ${#l2} -gt $2 ]] && l2="${l2:0:11}..."
	echo -e "$l1\n$l2"
}

ip=$(curl https://ipinfo.io/ip)
data=$(curl "https://ipinfo.io/$ip")
if [[ $1 = "location" ]]; then
	city=$(echo "$data" | jq '.city' | tr -d '"')
	[[ ! -n "$city" ]] && echo "~" || wrapline "$city" $lim
	exit 0
fi

loc=$(echo "$data" | jq '.loc' | tr -d '"')
lat=$(echo "$loc" | awk -F ',' '{printf "%.2f", $1}')
long=$(echo "$loc" | awk -F ',' '{printf "%.2f", $2}')
cm1=$(curl wttr.in/$lat,$long?format=%t-%c-%C 2> /dev/null) # suppress curl output
IFS="-" read -r temp icon cond <<< "$cm1" 2> /dev/null # suppress "Unknown..."
# echo $cm1

if [[ $icon = "" ]] || [[ $icon =~ [0-9] ]] ; then
	icon=""
	temp=""
	cond="Weather data not available"
fi

ICONS=("" "" "" "" "" "" "🌦")
if [[ $1 = "icon" ]]; then
	case $icon in
		⛅️*) echo "" ;;
		☀️*) echo "" ;;
		*) echo $icon ;;
	esac
elif [[ $1 = "temp" ]]; then
    echo $temp
elif [[ $1 = "cond" ]]; then
	[[ $2 != "short" ]] && echo $cond && exit 0
	wrapline "$cond" "$lim"

fi
