#!/bin/bash

HOME=/home/user
[[ $1 =~ ^(-h|--help)$ ]] && echo "cloud_sync [run] [onedrive/nextcloud] [me/personal]" && exit 0 

update_sync_tooltip() {
	eww update sync-tooltip="$HOME/.config/eww/scripts/tooltip sync"
}

# Check for wifi else notify to kill process
check_wifi() {
	[[ $(iwgetid -r) != "" ]] && return
	eww update sync-icon="$($HOME/.config/eww/scripts/geticon sync off)"
	update_sync_tooltip
	choice=$(dunstify -u critical --action="kill,Kill process" "Cloud sync failed" "WiFi not connected. Consider killing the cloud syncing process")
	[[ "$choice" != "kill" ]] && return
	notify-send -u low -i $HOME/.config/dunst/img/cloud_sync_stop.png "OneDrive and Nextcloud sync stopped"
	eww update sync-bool="false"
	exit 0
}

# Sync OneDrive
onedrive_sync() {
	err=/tmp/ONEERR
	SYNC_ME=1
	SYNC_IMP=1
	[[ $1 = "me" ]] && SYNC_IMP=0
	[[ $1 = "imperial" ]] && SYNC_ME=0
	if [[ $SYNC_ME = 1 ]] && [[ -d $HOME/OneDrive ]]; then
		onedrive --synchronize
	fi
	if [[ $SYNC_IMP = 1 ]] && [[ -d $HOME/Imperial ]]; then
		onedrive --synchronize --confdir=$HOME/.config/onedriveimperial 2>$err
		ERROR=$(<$err)
		[[ ! -n "$ERROR" ]] && rm $err && return
		choice=$(dunstify -u critical -i $HOME/.config/dunst/img/cloud_sync_stop.png --action="reauth,Reauthenticate OneDrive" "OneDrive Imperial not synced successfully" "Reauthenticate the account")
		[[ "$choice" = "reauth" ]] && alacritty --class floating -e onedrive --synchronize --confdir=$HOME/.config/onedriveimperial --reauth
		rm $err
	fi
}

# Sync Nextcloud
rem="/mnt/Nextcloud/"
loc="$HOME/Nextcloud/"
nextcloud_sync() {
	err=/tmp/NCERR
	[[ ! -n "$(ls -A $rem)" ]] && echo y | mount /mnt/Nextcloud # login details to save to /etc/davfs2/secrets
	/usr/local/bin/bsync $loc $rem 2>$err
	ERROR=$(<$err)
	[[ ! -n "$ERROR" ]] && rm $err && return
	choice=$(dunstify -u critical -i $HOME/.config/dunst/img/cloud_sync_stop.png --action="fix,Resync with fix" "Nextcloud not synced successfully")
	if [[ "$choice" = "fix" ]]; then
		rm $rem.bsync-snap* $loc.bsync-snap*
		/usr/local/bin/bsync $loc $rem
	fi
	rm $err
}

# Run once
if [[ $1 = "run" ]]; then
	SYNC_ONE=1
	SYNC_NC=1
	[[ $2 = "onedrive" ]] && SYNC_NC=0
	[[ $2 = "nextcloud" ]] && SYNC_ONE=0
	[[ $SYNC_ONE = 1 ]] && onedrive_sync "$3"
	[[ $SYNC_NC = 1 ]] && nextcloud_sync
	exit 0
fi

# Only allow one instance to run
notify-send -u low -i $HOME/.config/dunst/img/cloud_sync.png "OneDrive and Nextcloud sync started"
pid=$(pgrep `basename "$0"`)
[[ $(echo "$pid" | wc -l) -gt 1 ]] && exit 0

eww update sync-bool="true"
while true; do
	check_wifi

	eww update sync-icon="$($HOME/.config/eww/scripts/geticon sync syncing)"
	update_sync_tooltip
	onedrive_sync & nextcloud_sync
	eww update sync-icon="$($HOME/.config/eww/scripts/geticon sync)"
	eww update sync-start="$(date +%s)"
	update_sync_tooltip
	
	sleep 300
done
