#!/bin/bash

windows="$(eww windows) eol"
open_windows=$(echo "$(eww windows)" | grep "*")
ESC=9
RETURN=36

#echo "$open_windows"

if [[ "$(eww ping)" = "" ]]; then
	eww daemon
fi
close() {
	for pid in $(pgrep -f cava_output); do kill $pid; done
	eww close sidebar
	for i in $(seq 1 12); do eww update l$i=0; done
	eww open bar
	killall eww.sh
}

if [[ $1 != "" ]] && [[ $open_windows = *"$1"* ]]; then
	[ $1 = "bar" ] && eww close bar
	[ $1 = "sidebar" ] && close

elif [[ $1 = "sidebar" ]]; then
	$HOME/.config/eww/scripts/cava/cava_output &
	eww close bar
	eww open sidebar
	xinput test-xi2 --root 3 | grep -A2 --line-buffered RawKeyRelease | while read -r line; do
	    if [[ $line == *"detail"* ]]; then
	        key=$( echo $line | sed "s/[^0-9]*//g")
			if [[ $key = $ESC ]] || [[ $key = $RETURN ]]; then close; fi
		fi
	done

elif [[ $1 = "bar" ]]; then
	eww open bar

else
	close
fi
