#!/bin/bash
DUNST="$HOME/.config/dunst"
EWW="$HOME/.config/eww/scripts/getval"
TAG="fn"

# $1=icon, $2=value, $3=summary
alert() {
	notify-send -u "low" -i "$DUNST/img/$1.png" -h int:value:$2 -h string:x-dunst-stack-tag:$TAG -h "string:wired-tag:$TAG" "Current $3: $2%"
}

if [[ $1 = "vol" ]]; then
	val="$($EWW vol)"
	alert "volume-$2" $val "volume"

elif [[ $1 = "mute" ]]; then
	pactl set-sink-mute @DEFAULT_SINK@ toggle
	if [[ $2 != "notify" ]]; then exit 0; fi
	val="$($EWW vol)"
	if [[ $(pactl get-sink-mute @DEFAULT_SINK@) = "Mute: yes" ]]; then
		notify-send -u "low" -i "$DUNST/img/volume-mute.png" -h int:value:$val -h string:x-dunst-stack-tag:$TAG -h "string:wired-tag:$TAG" "Speakers muted"
	else
		notify-send -u "low" -i "$DUNST/img/volume-up.png" -h int:value:$val -h string:x-dunst-stack-tag:$TAG -h "string:wired-tag:$TAG" "Speakers unmuted"
	fi

elif [[ $1 = "light" ]]; then
	val="$($EWW light)"
	eww update light-val=$val
	eww update light-icon="$(~/.config/eww/scripts/geticon light)"
	alert "brightness-$2" $val "brightness"
fi
