#!/bin/bash

w=$(xdotool getdisplaygeometry | awk '{print $1}')
h=$(xdotool getdisplaygeometry | awk '{print $2}')
display_geometry="${w}x${h}"

check_fullscreen() {
	win_geometry=$(xdotool getactivewindow getwindowgeometry | grep "Geometry:" | awk '{print $2}')
	[[ $win_geometry = $display_geometry ]] && echo "true" || echo "false"
}
check_tray() {
	if i3-msg -t get_tree | grep -Fq '"class":"i3bar"'; then
		echo "true"
	else
		echo "false"
	fi
}

[[ $1 = "-p" ]] && check_fullscreen && exit 0

pid=$(pgrep fullscreen)
[[ $(echo "$pid" | wc -l) -gt 1 ]] && exit 0

prev="false"
c=0
i3-msg -t subscribe -m '[ "window" ]' | while read _; do
	val=$(check_fullscreen)
	if [[ $val != $prev ]]; then
		[[ $val = "true"]] &&
			eww close bar 2> /dev/null && i3-msg gaps left all set 0		
		[[ $val = "false" ]] && [[ $(check_tray) = "false" ]] &&
			eww open bar && i3-msg gaps left all set 50
	fi
	prev=$val
done

# vim: set ft=sh:
