#!/usr/bin/env python3
import pyautogui
import sys
text = sys.argv[1]
if text == "github":
	import rsa
	encrypted_msg = open('/home/user/dotfiles/keys/encrypted.txt','rb').read()
	private_key = rsa.PrivateKey.load_pkcs1(open('/home/user/dotfiles/keys/git.pem','r').read())
	text = rsa.decrypt(encrypted_msg, private_key).decode()

pyautogui.keyUp('alt')
pyautogui.write(text)
