#!/bin/bash

pid=$(pgrep network)
if [[ $(echo "$pid" | wc -l) -gt 1 ]]; then
    exit 0
fi

no_con_msg="There's no primary connection"

nmcli m | while read line; do
	[[ $line != *"primary connection"* ]] && continue
	# echo $line
	if [[ "$line" = "$no_con_msg" ]]; then
		eww update wifi-icon="睊"
		notify-send "Disconnected" "The network connection has been disconnected"
	else
		name=$(echo "$line" | awk -F"'" '{print $2}')
		[[ $name = "Wired Connection"* ]] && eww update wifi-icon="" || eww update wifi-icon="直"
		notify-send "Connection Established" "You are now connected to the Wi-Fi network \"$name\""
	fi
done
