#!/bin/bash

rem="/mnt/Nextcloud/"
loc="$HOME/Nextcloud/"
run() {
	[[ ! -n "$(ls -A $rem)" ]] && echo y | mount /mnt/Nextcloud # login details to save to /etc/davfs2/secrets
	/usr/local/bin/bsync $loc $rem
}

[[ $1 = "run" ]] && run && exit

pid=$(pgrep nextcloud)
[[ $(echo "$pid" | wc -l) -gt 1 ]] && exit 0
while true; do 
	run
	sleep 300
done
