#!/bin/bash

run() {
	/usr/local/bin/bsync ~/Nextcloud/ /mnt/Nextcloud/
}

[[ $1 = "run" ]] && run && exit

pid=$(pgrep nextcloud)
[[ $(echo "$pid" | wc -l) -gt 1 ]] && exit 0
while true; do 
	run
	sleep 300
done
