#!/bin/bash

notify-send -u low -i ~/.config/dunst/img/onedrive.png "OneDrive sync started"
pid=$(pgrep onedrive)
if [[ $(echo "$pid" | wc -l) -gt 1 ]]; then
	exit 0
fi

while true; do
	#check wifi
	if [[ $(iwgetid -r) = "" ]]; then
		choice=$(dunstify --action="kill,Kill process" "OneDrive sync failed" "WiFi not connected. Consider killing the OneDrive sync")
		case "$choice" in
			"kill")
				notify-send "OneDrive sync stopped"
				exit 0
				;;
		esac
	fi

	echo "pass"
	[[ -d ~/OneDrive ]] && onedrive --synchronize
	[[ -d ~/Imperial ]] && onedrive --synchronize --confdir=~/.config/onedriveimperial
	sleep 300
done
