#!/bin/bash

if [[ $1 = "run" ]]; then
	[[ ! -n $2 ]] && onedrive --synchronize
	[[ $2 = "imperial" ]] && onedrive --synchronize --confdir="~/.config/onedriveimperial"
	exit 0
fi

eww update sync-bool="true"
eww update sync-icon="$(~/.config/eww/scripts/geticon sync)"

while true; do
	if [[ ! -n $pid1 ]]; then
		onedrive --monitor &
		pid1=$!
	fi
	if [[ ! -n $pid2 ]]; then
		onedrive --monitor --confdir="~/.config/onedriveimperial" &
		pid2=$!
	fi
	sleep 30
done

# vim: set ft=sh:
