#!/bin/bash
l1="inactive-opacity = 1.0;"
l2="opacity-rule = \[\];"
l3="inactive-dim = 0;"
arr=("$l1" "$l2" "$l3")

CONF="$HOME/.config/picom/picom.conf"
pt=$(cat $CONF | grep "$l1" | awk '{print $1}')
[[ $pt = "#" ]] && status="enabled" || status="disabled"

[[ $1 = "-p" ]] && echo $status && exit 0

IFS=$'\n'
for l in ${arr[@]}; do
	ln=$(cat $CONF | grep -n "$l" | awk -F':' '{print $1}')
	[[ $status = "enabled" ]] && newline="$l" || newline="# $l"
	sed -i "${ln}s/.*/$newline/" $CONF
done

pkill -USR1 picom
# [[ $status = "enabled" ]] && newstatus="disabled" || newstatus="enabled"
# notify-send "Compositor $newstatus"
