#!/usr/bin/env bash
ROFIDIR="$HOME/.config/rofi"

# Options
shutdown=""
reboot=""
lock=""
suspend=""
logout=""

# Confirmation
confirm_exit() {
	rofi -dmenu\
		-i\
		-no-fixed-num-lines\
		-p "Are You Sure? : "\
		-theme $ROFIDIR/confirm.rasi
}

# Variable passed to rofi
options="$shutdown\n$reboot\n$suspend\n$lock\n$logout"

eww close sidebar 2> /dev/null
chosen="$(echo -e "$options" | rofi -p powermenu -theme $ROFIDIR/powermenu.rasi -dmenu -selected-row 2)"
case $chosen in
    $shutdown)
		ans=$(confirm_exit &)
		! [[ $ans =~ ^([yY]es|[yY])$ ]] && exit
		picom_toggle disable
		systemctl poweroff
	;;
    $reboot)
		ans=$(confirm_exit &)
		! [[ $ans =~ ^([yY]es|[yY])$ ]] && exit
		picom_toggle disable
		systemctl reboot
	;;
    $suspend)
		~/.config/i3/scripts/poweractions "sleep"
	;;
    $lock)
		~/.config/i3/scripts/poweractions lock
	;;
    $logout)
		ans=$(confirm_exit &)
		! [[ $ans =~ ^([yY]es|[yY])$ ]] && exit
		~/.config/i3/scripts/poweractions "exit"
	;;
esac
