#!/usr/bin/env bash
ROFIDIR="$HOME/.config/rofi"

# Options
shutdown=""
reboot=""
lock=""
suspend=""
logout=""

# Confirmation
confirm_exit() {
	rofi -dmenu\
		-i\
		-no-fixed-num-lines\
		-p "Are You Sure? : "\
		-theme $ROFIDIR/confirm.rasi
}

# Variable passed to rofi
options="$shutdown\n$reboot\n$lock\n$suspend\n$logout"

eww close sidebar 2> /dev/null
chosen="$(echo -e "$options" | rofi -p powermenu -theme $ROFIDIR/powermenu.rasi -dmenu -selected-row 2)"
eww open bar
case $chosen in
    $shutdown)
		ans=$(confirm_exit &)
		[[ $ans == "yes" || $ans == "YES" || $ans == "y" || $ans == "Y" ]] &&
			systemctl poweroff
	;;
    $reboot)
		ans=$(confirm_exit &)
		[[ $ans == "yes" || $ans == "YES" || $ans == "y" || $ans == "Y" ]] &&
			systemctl reboot
	;;
    $lock)
		~/.config/i3/scripts/poweractions lock
	;;
    $suspend)
		~/.config/i3/scripts/poweractions sleep
	;;
    $logout)
		ans=$(confirm_exit &)
		[[ $ans == "yes" || $ans == "YES" || $ans == "y" || $ans == "Y" ]] &&
			~/.config/i3/scripts/poweractions exit
	;;
esac
