#!/bin/bash

# keypress constants
ESC=9
RETURN=36

# start daemon if not started
[[ ! -n "$(eww ping)" ]] && eww daemon

close() {
	for pid in $(pgrep -f cava_output); do kill $pid; done
	eww update reveal-sidebar=false && sleep .2 && eww close sidebar
	for i in $(seq 1 12); do eww update l$i=0; done
	killall eww_controller
}

if ! [[ -n "$(eww windows | grep '*sidebar')" ]]; then
	$HOME/.config/eww/scripts/cava/cava_output &
	eww open sidebar && eww update reveal-sidebar=true
	xinput test-xi2 --root 3 | grep -A3 --line-buffered RawKeyRelease | while read -r line; do
	    if [[ $line == *"detail"* ]]; then
	        key=$( echo $line | sed "s/[^0-9]*//g")
			[[ $key =~ ^($ESC|$RETURN)$ ]] && close
		fi
	done

else
	close
fi
