#!/bin/bash

# keypress constants
ESC=9
RETURN=36

# start daemon if not started
[[ ! -n "$(eww ping)" ]] && eww daemon

close() {
	for pid in $(pgrep -f .*cava); do kill $pid; done
	rm /tmp/cava.fifo
	rm /tmp/bar_cava_config
	eww update reveal-sidebar=false && sleep .2 && eww close sidebar
	eww update cava="[3,3,3,3,3,3,3,3,3,3,3,3]"
	killall sidebar_toggle
}

if ! [[ -n "$(eww windows | grep '*sidebar')" ]]; then
	eww open sidebar && eww update reveal-sidebar=true
	xinput test-xi2 --root 3 | grep -A3 --line-buffered RawKeyRelease | while read -r line; do
	    if [[ $line == *"detail"* ]]; then
	        key=$( echo $line | sed "s/[^0-9]*//g")
			[[ $key =~ ^($ESC|$RETURN)$ ]] && close
		fi
	done

else
	close
fi
