#!/bin/bash

# Check for wifi else notify to kill process
check_wifi() {
	[[ $(iwgetid -r) != "" ]] && return
	choice=$(dunstify --action="kill,Kill process" "OneDrive sync failed" "WiFi not connected. Consider killing the OneDrive sync")
	case "$choice" in
		"kill")
			notify-send "OneDrive and Nextcloud sync stopped"
			eww update sync-bool="false"
			exit 0
			;;
	esac
}

# Sync OneDrive
onedrive_sync() {
	SYNC_ME=1
	SYNC_IMP=0
	[[ $1 = "imperial" ]] && SYNC_ME=0 && SYNC_IMP=1
	[[ $1 = "both" ]] && SYNC_IMP=1
	[[ $SYNC_ME = 1 ]] && [[ -d ~/OneDrive ]] && onedrive --synchronize
	[[ $SYNC_IMP = 1 ]] && [[ -d ~/Imperial ]] && onedrive --synchronize --confdir=~/.config/onedriveimperial
}

# Sync Nextcloud
rem="/mnt/Nextcloud/"
loc="$HOME/Nextcloud/"
nextcloud_sync() {
	[[ ! -n "$(ls -A $rem)" ]] && echo y | mount /mnt/Nextcloud # login details to save to /etc/davfs2/secrets
	/usr/local/bin/bsync $loc $rem
}

# Run once
if [[ $1 = "run" ]]; then
	SYNC_ONE=1
	SYNC_NC=1
	[[ $2 = "onedrive" ]] && SYNC_NC=0
	[[ $2 = "nextcloud" ]] && SYNC_ONE=0
	[[ $SYNC_ONE = 1 ]] && onedrive_sync "$3"
	[[ $SYNC_NC = 1 ]] && nextcloud_sync
	exit 0
fi

# Only allow one instance to run
notify-send -u low -i ~/.config/dunst/img/onedrive.png "OneDrive and Nextcloud sync started"
pid=$(pgrep `basename "$0"`)
[[ $(echo "$pid" | wc -l) -gt 1 ]] && exit 0

eww update sync-bool="true"
while true; do
	check_wifi

	eww update sync-icon="$(~/.config/eww/scripts/geticon sync syncing)"
	onedrive_sync
	nextcloud_sync
	eww update sync-icon="$(~/.config/eww/scripts/geticon sync)"
	
	sleep 300
done
