#!/bin/bash

XCONF="/etc/xsettingsd/xsettingsd.conf"
EWWCONF="$HOME/.config/eww/eww.scss"
ALACONF="$HOME/.config/alacritty/alacritty.yml"
I3CONF="$HOME/.config/i3/config"
ROFICONF="$HOME/.config/rofi/styles/colors.rasi"

if [[ -f $XCONF ]]; then
	theme=$(grep "Net/ThemeName" $XCONF | awk -F'"' '{print $2}')
	[[ "${theme,,}" = *"dark"* ]] && uu="Dark" || uu="Light"
else
	uu="Light"
fi
ll="$(echo $uu | tr '[:upper:]' '[:lower:]')"
[[ $ll = "dark" ]] && term_opacity=1.0 || term_opacity=0.9
[[ $1 = "-p" ]] && echo "$ll" && exit 0

DARK=""
LIGHT=""
[[ $ll = "light" ]] && SELECTED=0 || SELECTED=1
chosen=$(echo -e "$LIGHT\n$DARK" | rofi -dmenu -selected-row $SELECTED -theme ~/.config/rofi/theme.rasi)

case $chosen in
	$DARK)
		uu=Dark
		ll=dark
	;;
	$LIGHT)
		uu=Light
		ll=light
	;;
esac

feh --bg-fill ~/.config/i3/wallpapers/$ll-wallpaper.jpg
sed -i -e "s:@import .*:@import \"styles/$ll.scss\";:" $EWWCONF
sed -i -e "s:config/alacritty/.*:config/alacritty/$ll.yml:" $ALACONF
sed -i -e "s/opacity:.*/opacity: $term_opacity/" $ALACONF
sed -i -e "s/@import .*/@import \"$ll\"/g" $ROFICONF

inactive_bg=$(grep "inactive-bg-$ll" $I3CONF | awk '{print $3}')
inactive_text=$(grep "inactive-text-$ll" $I3CONF | awk '{print $3}')
sed -i -e "s/set \$inactive-bg.*/set \$inactive-bg\t\t$inactive_bg/g" $I3CONF
sed -i -e "s/set \$inactive-text.*/set \$inactive-text\t\t$inactive_text/g" $I3CONF

i3-msg reload
echo root | sudo -S sed -i -e "s:Net/ThemeName.*:Net/ThemeName \"Orchis-Purple-$uu\":" $XCONF
sudo killall -HUP xsettingsd
