#!/bin/bash

run() {
	val="$(~/.config/eww/scripts/getval vol)"
	bool="$(~/.config/eww/scripts/getbool mute)"
	[[ $(eww get volume-val) = $val ]] && [[ $(eww get mute-bool) = $bool ]] && return
	eww update volume-val=$val
	eww update mute-bool=$bool
	eww update vol-icon=$(~/.config/eww/scripts/geticon vol)
}

pactl subscribe | while read line; do
	[[ ! -n "$(echo $line | grep 'change')" ]] && continue
	run
done
