#!/bin/bash

DIR="$HOME/.config/eww/scripts/cava"
fifo="$DIR/fifo"
# f1="${f}1"
# f2="${f}2"
# f3="${f}3"
# f4="${f}4"
# f5="${f}5"
# f6="${f}6"
# f7="${f}7"
# f8="${f}8"
# f9="${f}9"
# f10="${f}10"
# f11="${f}11"

trap "rm -f $fifo" EXIT

$DIR/read_raw_output.py |
	while IFS= read -r line; do
		arr=($line)
		echo $line | tee $fifo >/dev/null
		# sleep 0.03
done
