#!/bin/bash
DIRS=(
	"Desktop shortcuts" "$HOME/.local/share/applications/user"
	"Desktop shortcuts" "/usr/share/applications"
	"Systemd services" "$HOME/.config/systemd/user"
	"Systemd services" "/etc/systemd/system"
	)
choice=$(printf "%s: %s\n" "${DIRS[@]}" | rofi -dmenu -theme ~/.config/rofi/dunst.rasi)

[[ ! -n $choice ]] && exit
echo ${choice##*: } | xclip -selection clipboard
xclip -selection clipboard -o
# alacritty --working-directory "${choice##*: }" --class floating,Alacritty

