#!/bin/bash
CONF="$HOME/.config/picom/picom.conf"
line=$(cat $CONF | grep -n '!focused')
num=$(echo "$line" | awk -F':' '{print $1}')
opacity=$(echo "$line" | awk -F':' '{print $2}' | tr -d '\t"')
[[ $opacity = 85 ]] && new_opacity=100 || new_opacity=85
# echo "${num}s/$opacity/$new_opacity/g"
sed -i "${num}s/$opacity/$new_opacity/g" $CONF

line=$(cat $CONF | grep -n 'inactive-dim')
num=$(echo "$line" | awk -F':' '{print $1}')
dim=$(echo "$line" | awk -F'=' '{print $2}' | tr -d ' ' | tr -d ';')
[[ $opacity = 85 ]] && new_dim=0 || new_dim=0.05
# echo "${num}s/$dim/$new_dim/g"
sed -i "${num}s/$dim/$new_dim/g" $CONF

